const themes = {
	'a11y-dark': require('highlight.js/styles/a11y-dark.css'),
	'a11y-light': require('highlight.js/styles/a11y-light.css'),
	'agate': require('highlight.js/styles/agate.css'),
	'an-old-hope': require('highlight.js/styles/an-old-hope.css'),
	'androidstudio': require('highlight.js/styles/androidstudio.css'),
	'arduino-light': require('highlight.js/styles/arduino-light.css'),
	'arta': require('highlight.js/styles/arta.css'),
	'ascetic': require('highlight.js/styles/ascetic.css'),
	'atelier-cave-dark': require('highlight.js/styles/atelier-cave-dark.css'),
	'atelier-cave-light': require('highlight.js/styles/atelier-cave-light.css'),
	'atelier-dune-dark': require('highlight.js/styles/atelier-dune-dark.css'),
	'atelier-dune-light': require('highlight.js/styles/atelier-dune-light.css'),
	'atelier-estuary-dark': require('highlight.js/styles/atelier-estuary-dark.css'),
	'atelier-estuary-light': require('highlight.js/styles/atelier-estuary-light.css'),
	'atelier-forest-dark': require('highlight.js/styles/atelier-forest-dark.css'),
	'atelier-forest-light': require('highlight.js/styles/atelier-forest-light.css'),
	'atelier-heath-dark': require('highlight.js/styles/atelier-heath-dark.css'),
	'atelier-heath-light': require('highlight.js/styles/atelier-heath-light.css'),
	'atelier-lakeside-dark': require('highlight.js/styles/atelier-lakeside-dark.css'),
	'atelier-lakeside-light': require('highlight.js/styles/atelier-lakeside-light.css'),
	'atelier-plateau-dark': require('highlight.js/styles/atelier-plateau-dark.css'),
	'atelier-plateau-light': require('highlight.js/styles/atelier-plateau-light.css'),
	'atelier-savanna-dark': require('highlight.js/styles/atelier-savanna-dark.css'),
	'atelier-savanna-light': require('highlight.js/styles/atelier-savanna-light.css'),
	'atelier-seaside-dark': require('highlight.js/styles/atelier-seaside-dark.css'),
	'atelier-seaside-light': require('highlight.js/styles/atelier-seaside-light.css'),
	'atelier-sulphurpool-dark': require('highlight.js/styles/atelier-sulphurpool-dark.css'),
	'atelier-sulphurpool-light': require('highlight.js/styles/atelier-sulphurpool-light.css'),
	'atom-one-dark-reasonable': require('highlight.js/styles/atom-one-dark-reasonable.css'),
	'atom-one-dark': require('highlight.js/styles/atom-one-dark.css'),
	'atom-one-light': require('highlight.js/styles/atom-one-light.css'),
	// 'brown-paper': require('highlight.js/styles/brown-paper.css'),
	'codepen-embed': require('highlight.js/styles/codepen-embed.css'),
	'color-brewer': require('highlight.js/styles/color-brewer.css'),
	'darcula': require('highlight.js/styles/darcula.css'),
	'dark': require('highlight.js/styles/dark.css'),
	'darkula': require('highlight.js/styles/darkula.css'),
	'default': require('highlight.js/styles/default.css'),
	'docco': require('highlight.js/styles/docco.css'),
	'dracula': require('highlight.js/styles/dracula.css'),
	'far': require('highlight.js/styles/far.css'),
	'foundation': require('highlight.js/styles/foundation.css'),
	'github-gist': require('highlight.js/styles/github-gist.css'),
	'github': require('highlight.js/styles/github.css'),
	'gml': require('highlight.js/styles/gml.css'),
	'googlecode': require('highlight.js/styles/googlecode.css'),
	'gradient-dark': require('highlight.js/styles/gradient-dark.css'),
	'grayscale': require('highlight.js/styles/grayscale.css'),
	'gruvbox-dark': require('highlight.js/styles/gruvbox-dark.css'),
	'gruvbox-light': require('highlight.js/styles/gruvbox-light.css'),
	'hopscotch': require('highlight.js/styles/hopscotch.css'),
	'hybrid': require('highlight.js/styles/hybrid.css'),
	'idea': require('highlight.js/styles/idea.css'),
	'ir-black': require('highlight.js/styles/ir-black.css'),
	'isbl-editor-dark': require('highlight.js/styles/isbl-editor-dark.css'),
	'isbl-editor-light': require('highlight.js/styles/isbl-editor-light.css'),
	'kimbie.dark': require('highlight.js/styles/kimbie.dark.css'),
	'kimbie.light': require('highlight.js/styles/kimbie.light.css'),
	'lightfair': require('highlight.js/styles/lightfair.css'),
	'magula': require('highlight.js/styles/magula.css'),
	'mono-blue': require('highlight.js/styles/mono-blue.css'),
	'monokai-sublime': require('highlight.js/styles/monokai-sublime.css'),
	'monokai': require('highlight.js/styles/monokai.css'),
	'night-owl': require('highlight.js/styles/night-owl.css'),
	'nord': require('highlight.js/styles/nord.css'),
	'obsidian': require('highlight.js/styles/obsidian.css'),
	'ocean': require('highlight.js/styles/ocean.css'),
	'paraiso-dark': require('highlight.js/styles/paraiso-dark.css'),
	'paraiso-light': require('highlight.js/styles/paraiso-light.css'),
	// 'pojoaque': require('highlight.js/styles/pojoaque.css'),
	'purebasic': require('highlight.js/styles/purebasic.css'),
	'qtcreator_dark': require('highlight.js/styles/qtcreator_dark.css'),
	'qtcreator_light': require('highlight.js/styles/qtcreator_light.css'),
	'railscasts': require('highlight.js/styles/railscasts.css'),
	'rainbow': require('highlight.js/styles/rainbow.css'),
	'routeros': require('highlight.js/styles/routeros.css'),
	// 'school-book': require('highlight.js/styles/school-book.css'),
	'shades-of-purple': require('highlight.js/styles/shades-of-purple.css'),
	'solarized-dark': require('highlight.js/styles/solarized-dark.css'),
	'solarized-light': require('highlight.js/styles/solarized-light.css'),
	'sunburst': require('highlight.js/styles/sunburst.css'),
	'tomorrow-night-blue': require('highlight.js/styles/tomorrow-night-blue.css'),
	'tomorrow-night-bright': require('highlight.js/styles/tomorrow-night-bright.css'),
	'tomorrow-night-eighties': require('highlight.js/styles/tomorrow-night-eighties.css'),
	'tomorrow-night': require('highlight.js/styles/tomorrow-night.css'),
	'tomorrow': require('highlight.js/styles/tomorrow.css'),
	'vs': require('highlight.js/styles/vs.css'),
	'vs2015': require('highlight.js/styles/vs2015.css'),
	'xcode': require('highlight.js/styles/xcode.css'),
	'xt256': require('highlight.js/styles/xt256.css'),
	'zenburn': require('highlight.js/styles/zenburn.css'),
}

const THEME_CODES = Object.keys(themes)

export default ((theme, dfault = 'nord') => themes[theme] || themes[dfault])

export {
	THEME_CODES,
}